version: '2'

networks:
  keycloak-network:

volumes:
    keycloak-postgres-data:
        driver_opts:
            type: none
            device: $PWD/${POSTGRES_DATA_PATH}
            o: bind
    keycloak-nginx-ssl:
        driver: local
        driver_opts:
            type: none
            device: $PWD/${KEYCLOAK_DATA_PATH}
            o: bind

services:
  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    container_name: postgres
    networks:
      - keycloak-network
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD
    restart: unless-stopped
  keycloak:
    image: "jboss/keycloak:${KEYCLOAK_VERSION}"
    container_name: keycloak
    links:
      - postgres
    networks:
      - keycloak-network
    depends_on:
      - postgres
    environment:
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD
      # JBoss is using legacy linking environment variables
      - POSTGRES_PORT_5432_TCP_ADDR=postgres
      - POSTGRES_PORT_5432_TCP_PORT=5432
    restart: unless-stopped
  nginx:
    image: ernsheong/keycloak-nginx-self-ssl
    container_name: nginx
    networks:
      - keycloak-network
    depends_on:
      - keycloak
    volumes:
      - keycloak-nginx-ssl:/etc/nginx/ssl
    environment:
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_DOMAIN=www.example.com
    ports:
      - "443:443"
    restart: unless-stopped
